### ISSUE TITLE
Firebase Reported Crash AdvertisingIdentifierPlugin.java line 2

### ISSUE THREAD

**Issue by Jai05-techie** [RxReader/advertising_identifier#2]
Hi,

I'm using the `advertising_identifier:^0.1.1` plugin version. Recently released Android application heads up more crashes with AdvertisingIdentifierPlugin.java.

**_Error reported in crashlytics,_**

```
Fatal Exception: java.lang.NullPointerException: null reference
       at com.google.android.gms.common.internal.Preconditions.a(Preconditions.java:7)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.<init>(AdvertisingIdClient.java:10)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.a(AdvertisingIdClient.java:8)
       at io.github.v7lin.advertising_identifier.AdvertisingIdentifierPlugin$1.run(AdvertisingIdentifierPlugin.java:2)
       at java.lang.Thread.run(Thread.java:923)
```
<img width="1145" alt="Screenshot 2022-03-21 at 3 20 03 PM" src="https://user-images.githubusercontent.com/62050139/159237883-5c70cee4-91c9-4ca9-925a-fc2c2c82c962.png">

Any solution ? Thanks in advance

**Comment by v7lin** [comment]
fix
